"""phase 1 executor baseline

Revision ID: 5b313abfb3fa
Revises: 
Create Date: 2026-07-02 10:49:58.484405

"""
import importlib

from alembic import op
import sqlalchemy as sa

# NB: ``app.models`` does ``from __future__ import annotations``, which shadows the
# ``annotations`` submodule name, so a normal ``import app.models.annotations`` (or
# ``... as``) resolves to ``__future__.annotations``. Load it from sys.modules instead.
orbit_types = importlib.import_module("app.models.annotations")


# revision identifiers, used by Alembic.
revision = '5b313abfb3fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_events',
    sa.Column('event', orbit_types.CITEXT(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', orbit_types.CITEXT(), nullable=False),
    sa.Column('extra', orbit_types.JSONB(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_events')),
    sa.UniqueConstraint('uuid', name=op.f('uq_app_events_uuid'))
    )
    with op.batch_alter_table('app_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_events_app_events_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('compliance_policies',
    sa.Column('name', orbit_types.CITEXT(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', orbit_types.JSONB(), nullable=False),
    sa.Column('rules', orbit_types.JSONB(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_policies')),
    sa.UniqueConstraint('name', name=op.f('uq_compliance_policies_name')),
    sa.UniqueConstraint('uuid', name=op.f('uq_compliance_policies_uuid'))
    )
    with op.batch_alter_table('compliance_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_policies_compliance_policies_disabled_at'), ['disabled_at'], unique=False)

    op.create_table('credential_profiles',
    sa.Column('name', orbit_types.CITEXT(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('auth_type', orbit_types.CITEXT(), nullable=False),
    sa.Column('username', orbit_types.CITEXT(), nullable=True),
    sa.Column('secret_ref', sa.String(), nullable=True),
    sa.Column('secret_metadata', orbit_types.JSONB(), nullable=False),
    sa.Column('params', orbit_types.JSONB(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credential_profiles')),
    sa.UniqueConstraint('uuid', name=op.f('uq_credential_profiles_uuid'))
    )
    with op.batch_alter_table('credential_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credential_profiles_credential_profiles_disabled_at'), ['disabled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_credential_profiles_credential_profiles_name'), ['name'], unique=True)

    op.create_table('device_probe_templates',
    sa.Column('slug', orbit_types.CITEXT(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('probe_type', orbit_types.CITEXT(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('config', orbit_types.JSONB(), nullable=False),
    sa.Column('expected_outcome', orbit_types.JSONB(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_probe_templates')),
    sa.UniqueConstraint('uuid', name=op.f('uq_device_probe_templates_uuid'))
    )
    with op.batch_alter_table('device_probe_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_probe_templates_device_probe_templates_disabled_at'), ['disabled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_probe_templates_device_probe_templates_slug'), ['slug'], unique=True)

    op.create_table('device_tags',
    sa.Column('slug', orbit_types.CITEXT(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('attributes', orbit_types.JSONB(), nullable=False),
    sa.Column('is_protected', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_tags')),
    sa.UniqueConstraint('uuid', name=op.f('uq_device_tags_uuid'))
    )
    with op.batch_alter_table('device_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_tags_device_tags_slug'), ['slug'], unique=True)
        batch_op.create_index('ix_device_tags_slug', ['slug'], unique=False)

    op.create_table('device_types',
    sa.Column('name', orbit_types.CITEXT(), nullable=False),
    sa.Column('category', orbit_types.CITEXT(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_types')),
    sa.UniqueConstraint('name', name=op.f('uq_device_types_name')),
    sa.UniqueConstraint('uuid', name=op.f('uq_device_types_uuid'))
    )
    op.create_table('inventory_groups',
    sa.Column('slug', orbit_types.CITEXT(), nullable=False),
    sa.Column('name', orbit_types.CITEXT(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nornir_data', orbit_types.JSONB(), nullable=False),
    sa.Column('ansible_vars', orbit_types.JSONB(), nullable=False),
    sa.Column('is_dynamic', sa.Boolean(), nullable=False),
    sa.Column('definition', orbit_types.JSONB(), nullable=False),
    sa.Column('evaluation_scope', orbit_types.CITEXT(), nullable=True),
    sa.Column('cached_device_count', sa.Integer(), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_groups')),
    sa.UniqueConstraint('name', name=op.f('uq_inventory_groups_name')),
    sa.UniqueConstraint('uuid', name=op.f('uq_inventory_groups_uuid'))
    )
    with op.batch_alter_table('inventory_groups', schema=None) as batch_op:
        batch_op.create_index('ix_inventory_groups_dynamic', ['is_dynamic', 'disabled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_groups_inventory_groups_disabled_at'), ['disabled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_groups_inventory_groups_slug'), ['slug'], unique=True)

    op.create_table('login_attempts',
    sa.Column('username', orbit_types.CITEXT(), nullable=False),
    sa.Column('ip_address', orbit_types.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=128), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts')),
    sa.UniqueConstraint('uuid', name=op.f('uq_login_attempts_uuid'))
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_login_attempts_ip_created', ['ip_address', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_login_attempts_username'), ['username'], unique=False)
        batch_op.create_index('ix_login_attempts_username_created', ['username', 'created_at'], unique=False)

    op.create_table('manufacturers',
    sa.Column('name', orbit_types.CITEXT(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manufacturers')),
    sa.UniqueConstraint('name', name=op.f('uq_manufacturers_name')),
    sa.UniqueConstraint('uuid', name=op.f('uq_manufacturers_uuid'))
    )
    op.create_table('platforms',
    sa.Column('slug', orbit_types.CITEXT(), nullable=False),
    sa.Column('display_name', orbit_types.CITEXT(), nullable=True),
    sa.Column('vendor_hint', orbit_types.CITEXT(), nullable=True),
    sa.Column('napalm_driver', sa.String(), nullable=True),
    sa.Column('napalm_optional_args', orbit_types.JSONB(), nullable=False),
    sa.Column('netmiko_type', sa.String(), nullable=True),
    sa.Column('scrapli_platform', sa.String(), nullable=True),
    sa.Column('default_transport', orbit_types.CITEXT(), nullable=True),
    sa.Column('handler_entrypoint', sa.String(), nullable=True),
    sa.Column('extras', orbit_types.JSONB(), nullable=False),
    sa.Column('ansible_network_os', orbit_types.CITEXT(), nullable=True),
    sa.Column('ansible_connection', orbit_types.CITEXT(), nullable=True),
    sa.Column('ansible_vars', orbit_types.JSONB(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platforms')),
    sa.UniqueConstraint('uuid', name=op.f('uq_platforms_uuid'))
    )
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platforms_platforms_disabled_at'), ['disabled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_platforms_platforms_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('username', orbit_types.CITEXT(), nullable=False),
    sa.Column('email', orbit_types.CITEXT(), nullable=True),
    sa.Column('roles', orbit_types.JSONB(), nullable=False),
    sa.Column('jwt_auth_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('uuid', name=op.f('uq_users_uuid'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_users_disabled_at'), ['disabled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_users_username'), ['username'], unique=True)

    op.create_table('compliance_rules',
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('params', orbit_types.JSONB(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['compliance_policies.id'], name=op.f('fk_compliance_rules_policy_id_compliance_policies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_rules')),
    sa.UniqueConstraint('uuid', name=op.f('uq_compliance_rules_uuid'))
    )
    with op.batch_alter_table('compliance_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_rules_compliance_rules_policy_id'), ['policy_id'], unique=False)

    op.create_table('jwt_token_blocklist',
    sa.Column('jwt_token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_jwt_token_blocklist_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jwt_token_blocklist')),
    sa.UniqueConstraint('uuid', name=op.f('uq_jwt_token_blocklist_uuid'))
    )
    with op.batch_alter_table('jwt_token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jwt_token_blocklist_jwt_token_blocklist_jwt_token'), ['jwt_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_jwt_token_blocklist_jwt_token_blocklist_user_id'), ['user_id'], unique=False)

    op.create_table('platform_operation_templates',
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('op_type', orbit_types.CITEXT(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('variables', orbit_types.JSONB(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('fk_platform_operation_templates_platform_id_platforms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_operation_templates')),
    sa.UniqueConstraint('platform_id', 'op_type', 'name', name='uq_platform_op_template'),
    sa.UniqueConstraint('uuid', name=op.f('uq_platform_operation_templates_uuid'))
    )
    with op.batch_alter_table('platform_operation_templates', schema=None) as batch_op:
        batch_op.create_index('ix_platform_op', ['platform_id', 'op_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_operation_templates_platform_operation_templates_op_type'), ['op_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_operation_templates_platform_operation_templates_platform_id'), ['platform_id'], unique=False)

    op.create_table('product_models',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('name', orbit_types.CITEXT(), nullable=False),
    sa.Column('model_number', orbit_types.CITEXT(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], name=op.f('fk_product_models_manufacturer_id_manufacturers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_models')),
    sa.UniqueConstraint('manufacturer_id', 'name', name='uq_model_per_mfg'),
    sa.UniqueConstraint('uuid', name=op.f('uq_product_models_uuid'))
    )
    op.create_table('request_logs',
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('route', sa.String(), nullable=True),
    sa.Column('blueprint', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('request_bytes', sa.Integer(), nullable=True),
    sa.Column('response_bytes', sa.Integer(), nullable=True),
    sa.Column('auth_subject', sa.String(), nullable=True),
    sa.Column('device_id_hint', sa.Integer(), nullable=True),
    sa.Column('platform_id_hint', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('query_params', orbit_types.JSONB(), nullable=False),
    sa.Column('request_headers', orbit_types.JSONB(), nullable=False),
    sa.Column('response_headers', orbit_types.JSONB(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_request_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_logs')),
    sa.UniqueConstraint('uuid', name=op.f('uq_request_logs_uuid'))
    )
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_logs_request_logs_auth_subject'), ['auth_subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_request_logs_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_request_logs_device_id_hint'), ['device_id_hint'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_request_logs_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_request_logs_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_request_logs_platform_id_hint'), ['platform_id_hint'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_request_logs_status_code'), ['status_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_request_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_requestlogs_path', ['path'], unique=False)
        batch_op.create_index('ix_requestlogs_status', ['status_code'], unique=False)
        batch_op.create_index('ix_requestlogs_time', ['occurred_at'], unique=False)
        batch_op.create_index('ix_requestlogs_user', ['user_id'], unique=False)

    op.create_table('software_lifecycle',
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('os_name', orbit_types.CITEXT(), nullable=False),
    sa.Column('match_value', sa.String(), nullable=False),
    sa.Column('match_operator', orbit_types.CITEXT(), nullable=False),
    sa.Column('end_of_software_maintenance_date', sa.DateTime(), nullable=True),
    sa.Column('end_of_security_fixes_date', sa.DateTime(), nullable=True),
    sa.Column('last_day_of_support_date', sa.DateTime(), nullable=True),
    sa.Column('end_of_sale_date', sa.DateTime(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("match_operator IN ('eq','prefix','regex')", name=op.f('ck_software_lifecycle_chk_softlife_match_op')),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('fk_software_lifecycle_platform_id_platforms'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_software_lifecycle')),
    sa.UniqueConstraint('uuid', name=op.f('uq_software_lifecycle_uuid'))
    )
    with op.batch_alter_table('software_lifecycle', schema=None) as batch_op:
        batch_op.create_index('ix_softlife_match', ['match_operator', 'match_value'], unique=False)
        batch_op.create_index('ix_softlife_os_platform', ['os_name', 'platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_software_lifecycle_software_lifecycle_os_name'), ['os_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_software_lifecycle_software_lifecycle_platform_id'), ['platform_id'], unique=False)

    op.create_table('devices',
    sa.Column('name', orbit_types.CITEXT(), nullable=True),
    sa.Column('fqdn', orbit_types.CITEXT(), nullable=True),
    sa.Column('device_type_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('product_model_id', sa.Integer(), nullable=True),
    sa.Column('serial_number', orbit_types.CITEXT(), nullable=True),
    sa.Column('asset_tag', orbit_types.CITEXT(), nullable=True),
    sa.Column('is_virtual', sa.Boolean(), nullable=False),
    sa.Column('os_name', orbit_types.CITEXT(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('mgmt_ipv4', orbit_types.INET(), nullable=True),
    sa.Column('mgmt_port', sa.Integer(), nullable=False),
    sa.Column('facts', orbit_types.JSONB(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('credential_profile_id', sa.Integer(), nullable=True),
    sa.Column('nornir_data', orbit_types.JSONB(), nullable=False),
    sa.Column('ansible_host', orbit_types.CITEXT(), nullable=True),
    sa.Column('ansible_vars', orbit_types.JSONB(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(mgmt_port IS NULL) OR (mgmt_port > 0 AND mgmt_port <= 65535)', name=op.f('ck_devices_chk_devices_mgmt_port')),
    sa.ForeignKeyConstraint(['credential_profile_id'], ['credential_profiles.id'], name=op.f('fk_devices_credential_profile_id_credential_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_type_id'], ['device_types.id'], name=op.f('fk_devices_device_type_id_device_types'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], name=op.f('fk_devices_manufacturer_id_manufacturers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('fk_devices_platform_id_platforms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_model_id'], ['product_models.id'], name=op.f('fk_devices_product_model_id_product_models'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('uuid', name=op.f('uq_devices_uuid'))
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_devices_disabled_at'), ['disabled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_devices_fqdn'), ['fqdn'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_devices_mgmt_ipv4'), ['mgmt_ipv4'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_devices_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_devices_serial_number'), ['serial_number'], unique=False)

    op.create_table('error_logs',
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('level', orbit_types.CITEXT(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('request_log_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('context', orbit_types.JSONB(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_log_id'], ['request_logs.id'], name=op.f('fk_error_logs_request_log_id_request_logs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_error_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_logs')),
    sa.UniqueConstraint('uuid', name=op.f('uq_error_logs_uuid'))
    )
    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_logs_error_logs_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_logs_error_logs_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_logs_error_logs_user_id'), ['user_id'], unique=False)

    op.create_table('hardware_lifecycle',
    sa.Column('product_model_id', sa.Integer(), nullable=False),
    sa.Column('end_of_sale_date', sa.DateTime(), nullable=True),
    sa.Column('end_of_software_maintenance_date', sa.DateTime(), nullable=True),
    sa.Column('end_of_security_fixes_date', sa.DateTime(), nullable=True),
    sa.Column('last_day_of_support_date', sa.DateTime(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_model_id'], ['product_models.id'], name=op.f('fk_hardware_lifecycle_product_model_id_product_models'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hardware_lifecycle')),
    sa.UniqueConstraint('uuid', name=op.f('uq_hardware_lifecycle_uuid'))
    )
    with op.batch_alter_table('hardware_lifecycle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hardware_lifecycle_hardware_lifecycle_product_model_id'), ['product_model_id'], unique=True)

    op.create_table('jobs',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('job_type', orbit_types.CITEXT(), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('queue', orbit_types.CITEXT(), nullable=True),
    sa.Column('status', orbit_types.CITEXT(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('progress_completed', sa.Integer(), nullable=False),
    sa.Column('parameters', orbit_types.JSONB(), nullable=False),
    sa.Column('result', orbit_types.JSONB(), nullable=False),
    sa.Column('error', orbit_types.JSONB(), nullable=False),
    sa.Column('run_as_internal', sa.Boolean(), nullable=False),
    sa.Column('operation_template_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['operation_template_id'], ['platform_operation_templates.id'], name=op.f('fk_jobs_operation_template_id_platform_operation_templates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_jobs_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('uuid', name=op.f('uq_jobs_uuid'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_jobs_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_jobs_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_jobs_operation_template_id'), ['operation_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_jobs_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_jobs_queue'), ['queue'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_jobs_scheduled_for'), ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_jobs_type_status', ['job_type', 'status'], unique=False)

    op.create_table('audit_log_entries',
    sa.Column('actor_type', orbit_types.CITEXT(), nullable=True),
    sa.Column('actor_display_name', sa.String(length=255), nullable=True),
    sa.Column('action', orbit_types.CITEXT(), nullable=False),
    sa.Column('target_type', orbit_types.CITEXT(), nullable=False),
    sa.Column('target_uuid', sa.String(length=36), nullable=True),
    sa.Column('target_repr', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', orbit_types.JSONB(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_log_entries_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_audit_log_entries_job_id_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log_entries')),
    sa.UniqueConstraint('uuid', name=op.f('uq_audit_log_entries_uuid'))
    )
    with op.batch_alter_table('audit_log_entries', schema=None) as batch_op:
        batch_op.create_index('ix_audit_actor', ['actor_id', 'action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entries_audit_log_entries_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entries_audit_log_entries_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entries_audit_log_entries_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entries_audit_log_entries_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entries_audit_log_entries_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entries_audit_log_entries_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entries_audit_log_entries_target_type'), ['target_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entries_audit_log_entries_target_uuid'), ['target_uuid'], unique=False)
        batch_op.create_index('ix_audit_target', ['target_type', 'target_id'], unique=False)

    op.create_table('device_config_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('captured_by_id', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('source', orbit_types.CITEXT(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_inline', sa.Boolean(), nullable=False),
    sa.Column('content_inline_text', sa.Text(), nullable=True),
    sa.Column('content_inline_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('object_url', sa.String(), nullable=True),
    sa.Column('content_mime', sa.String(), nullable=False),
    sa.Column('content_encoding', sa.String(), nullable=True),
    sa.Column('vendor_hint', orbit_types.CITEXT(), nullable=True),
    sa.Column('config_role', orbit_types.CITEXT(), nullable=True),
    sa.Column('parsed_facts', orbit_types.JSONB(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['captured_by_id'], ['users.id'], name=op.f('fk_device_config_snapshots_captured_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_config_snapshots_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_device_config_snapshots_job_id_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_config_snapshots')),
    sa.UniqueConstraint('device_id', 'content_sha256', name='uq_config_dedup'),
    sa.UniqueConstraint('uuid', name=op.f('uq_device_config_snapshots_uuid'))
    )
    with op.batch_alter_table('device_config_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_config_device_time', ['device_id', 'captured_at'], unique=False)
        batch_op.create_index('ix_config_job', ['job_id', 'captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_config_snapshots_device_config_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_config_snapshots_device_config_snapshots_captured_by_id'), ['captured_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_config_snapshots_device_config_snapshots_content_sha256'), ['content_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_config_snapshots_device_config_snapshots_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_config_snapshots_device_config_snapshots_job_id'), ['job_id'], unique=False)

    op.create_table('device_inventory_groups',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_inventory_groups_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['inventory_groups.id'], name=op.f('fk_device_inventory_groups_group_id_inventory_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', 'group_id', name=op.f('pk_device_inventory_groups'))
    )
    op.create_table('device_tag_assignments',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('applied_by_id', sa.Integer(), nullable=True),
    sa.Column('source', orbit_types.CITEXT(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attributes', orbit_types.JSONB(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['applied_by_id'], ['users.id'], name=op.f('fk_device_tag_assignments_applied_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_tag_assignments_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_device_tag_assignments_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tag_id'], ['device_tags.id'], name=op.f('fk_device_tag_assignments_tag_id_device_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_tag_assignments')),
    sa.UniqueConstraint('device_id', 'tag_id', name='uq_device_tag'),
    sa.UniqueConstraint('uuid', name=op.f('uq_device_tag_assignments_uuid'))
    )
    with op.batch_alter_table('device_tag_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_tag_assignments_device_tag_assignments_applied_by_id'), ['applied_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_tag_assignments_device_tag_assignments_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_tag_assignments_device_tag_assignments_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_tag_assignments_device_tag_assignments_tag_id'), ['tag_id'], unique=False)

    op.create_table('interfaces',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('type', orbit_types.CITEXT(), nullable=True),
    sa.Column('speed_mbps', sa.Integer(), nullable=True),
    sa.Column('is_up', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('mtu', sa.Integer(), nullable=True),
    sa.Column('facts', orbit_types.JSONB(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_interfaces_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interfaces')),
    sa.UniqueConstraint('device_id', 'name', name='uq_interface_per_device'),
    sa.UniqueConstraint('uuid', name=op.f('uq_interfaces_uuid'))
    )
    with op.batch_alter_table('interfaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interfaces_interfaces_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interfaces_interfaces_mac_address'), ['mac_address'], unique=False)

    op.create_table('job_events',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('event_type', orbit_types.CITEXT(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('context', orbit_types.JSONB(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_events_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_events')),
    sa.UniqueConstraint('uuid', name=op.f('uq_job_events_uuid'))
    )
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_events_job_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_events_job_events_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_events_job_events_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('job_tasks',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('task_type', orbit_types.CITEXT(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', orbit_types.CITEXT(), nullable=False),
    sa.Column('target_type', orbit_types.CITEXT(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('progress_completed', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('parameters', orbit_types.JSONB(), nullable=False),
    sa.Column('result', orbit_types.JSONB(), nullable=False),
    sa.Column('error', orbit_types.JSONB(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_job_tasks_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['inventory_groups.id'], name=op.f('fk_job_tasks_group_id_inventory_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_tasks_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_tasks')),
    sa.UniqueConstraint('job_id', 'sequence', name='uq_jobtask_sequence'),
    sa.UniqueConstraint('uuid', name=op.f('uq_job_tasks_uuid'))
    )
    with op.batch_alter_table('job_tasks', schema=None) as batch_op:
        batch_op.create_index('ix_job_tasks_device', ['device_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_tasks_job_tasks_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_tasks_job_tasks_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_tasks_job_tasks_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_tasks_job_tasks_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_tasks_job_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_tasks_job_tasks_task_type'), ['task_type'], unique=False)

    op.create_table('physical_device_infos',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('site', orbit_types.CITEXT(), nullable=True),
    sa.Column('rack', sa.String(), nullable=True),
    sa.Column('position_u', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_physical_device_infos_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', name=op.f('pk_physical_device_infos'))
    )
    op.create_table('virtual_instance_infos',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('hypervisor', orbit_types.CITEXT(), nullable=True),
    sa.Column('host_device_id', sa.Integer(), nullable=True),
    sa.Column('vm_uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_virtual_instance_infos_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_device_id'], ['devices.id'], name=op.f('fk_virtual_instance_infos_host_device_id_devices'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('device_id', name=op.f('pk_virtual_instance_infos'))
    )
    with op.batch_alter_table('virtual_instance_infos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_virtual_instance_infos_virtual_instance_infos_vm_uuid'), ['vm_uuid'], unique=False)

    op.create_table('compliance_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('is_compliant', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('details', orbit_types.JSONB(), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_compliance_results_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['compliance_policies.id'], name=op.f('fk_compliance_results_policy_id_compliance_policies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['compliance_rules.id'], name=op.f('fk_compliance_results_rule_id_compliance_rules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['device_config_snapshots.id'], name=op.f('fk_compliance_results_snapshot_id_device_config_snapshots'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_results'))
    )
    with op.batch_alter_table('compliance_results', schema=None) as batch_op:
        batch_op.create_index('ix_compliance_device_time', ['device_id', 'checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_results_compliance_results_checked_at'), ['checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_results_compliance_results_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_results_compliance_results_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_results_compliance_results_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('device_config_diffs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('from_snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('to_snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('diff_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_config_diffs_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_snapshot_id'], ['device_config_snapshots.id'], name=op.f('fk_device_config_diffs_from_snapshot_id_device_config_snapshots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_snapshot_id'], ['device_config_snapshots.id'], name=op.f('fk_device_config_diffs_to_snapshot_id_device_config_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_config_diffs'))
    )
    with op.batch_alter_table('device_config_diffs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_config_diffs_device_config_diffs_device_id'), ['device_id'], unique=False)

    op.create_table('device_health_snapshots',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', orbit_types.CITEXT(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metrics', orbit_types.JSONB(), nullable=False),
    sa.Column('checks', orbit_types.JSONB(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('availability_percent', sa.Float(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('job_task_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_health_snapshots_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_device_health_snapshots_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_task_id'], ['job_tasks.id'], name=op.f('fk_device_health_snapshots_job_task_id_job_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_health_snapshots')),
    sa.UniqueConstraint('uuid', name=op.f('uq_device_health_snapshots_uuid'))
    )
    with op.batch_alter_table('device_health_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_device_health_latest', ['device_id', 'observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_health_snapshots_device_health_snapshots_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_health_snapshots_device_health_snapshots_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_health_snapshots_device_health_snapshots_job_task_id'), ['job_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_health_snapshots_device_health_snapshots_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_health_snapshots_device_health_snapshots_status'), ['status'], unique=False)

    op.create_table('device_probe_executions',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('job_task_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('probe_type', orbit_types.CITEXT(), nullable=False),
    sa.Column('status', orbit_types.CITEXT(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('response', orbit_types.JSONB(), nullable=False),
    sa.Column('diagnostics', orbit_types.JSONB(), nullable=False),
    sa.Column('error', orbit_types.JSONB(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_probe_executions_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_device_probe_executions_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_task_id'], ['job_tasks.id'], name=op.f('fk_device_probe_executions_job_task_id_job_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['device_probe_templates.id'], name=op.f('fk_device_probe_executions_template_id_device_probe_templates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_probe_executions')),
    sa.UniqueConstraint('uuid', name=op.f('uq_device_probe_executions_uuid'))
    )
    with op.batch_alter_table('device_probe_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_probe_executions_device_probe_executions_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_probe_executions_device_probe_executions_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_probe_executions_device_probe_executions_job_task_id'), ['job_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_probe_executions_device_probe_executions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_probe_executions_device_probe_executions_template_id'), ['template_id'], unique=False)
        batch_op.create_index('ix_probe_job', ['job_id', 'job_task_id'], unique=False)
        batch_op.create_index('ix_probe_status', ['status', 'probe_type'], unique=False)

    op.create_table('ip_addresses',
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('interface_id', sa.Integer(), nullable=True),
    sa.Column('address', orbit_types.INET(), nullable=False),
    sa.Column('prefix_length', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('role', orbit_types.CITEXT(), nullable=True),
    sa.Column('vrf', orbit_types.CITEXT(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('meta', orbit_types.JSONB(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_ip_addresses_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interface_id'], ['interfaces.id'], name=op.f('fk_ip_addresses_interface_id_interfaces'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ip_addresses')),
    sa.UniqueConstraint('address', name=op.f('uq_ip_addresses_address')),
    sa.UniqueConstraint('uuid', name=op.f('uq_ip_addresses_uuid'))
    )
    with op.batch_alter_table('ip_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ip_addresses_ip_addresses_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ip_addresses_ip_addresses_interface_id'), ['interface_id'], unique=False)

    op.create_table('interface_ip_addresses',
    sa.Column('interface_id', sa.Integer(), nullable=False),
    sa.Column('ip_address_id', sa.Integer(), nullable=False),
    sa.Column('primary', sa.Boolean(), nullable=False),
    sa.Column('assigned_from', sa.DateTime(), nullable=True),
    sa.Column('assigned_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['interface_id'], ['interfaces.id'], name=op.f('fk_interface_ip_addresses_interface_id_interfaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ip_address_id'], ['ip_addresses.id'], name=op.f('fk_interface_ip_addresses_ip_address_id_ip_addresses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('interface_id', 'ip_address_id', name=op.f('pk_interface_ip_addresses'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interface_ip_addresses')
    with op.batch_alter_table('ip_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ip_addresses_ip_addresses_interface_id'))
        batch_op.drop_index(batch_op.f('ix_ip_addresses_ip_addresses_device_id'))

    op.drop_table('ip_addresses')
    with op.batch_alter_table('device_probe_executions', schema=None) as batch_op:
        batch_op.drop_index('ix_probe_status')
        batch_op.drop_index('ix_probe_job')
        batch_op.drop_index(batch_op.f('ix_device_probe_executions_device_probe_executions_template_id'))
        batch_op.drop_index(batch_op.f('ix_device_probe_executions_device_probe_executions_status'))
        batch_op.drop_index(batch_op.f('ix_device_probe_executions_device_probe_executions_job_task_id'))
        batch_op.drop_index(batch_op.f('ix_device_probe_executions_device_probe_executions_job_id'))
        batch_op.drop_index(batch_op.f('ix_device_probe_executions_device_probe_executions_device_id'))

    op.drop_table('device_probe_executions')
    with op.batch_alter_table('device_health_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_health_snapshots_device_health_snapshots_status'))
        batch_op.drop_index(batch_op.f('ix_device_health_snapshots_device_health_snapshots_observed_at'))
        batch_op.drop_index(batch_op.f('ix_device_health_snapshots_device_health_snapshots_job_task_id'))
        batch_op.drop_index(batch_op.f('ix_device_health_snapshots_device_health_snapshots_job_id'))
        batch_op.drop_index(batch_op.f('ix_device_health_snapshots_device_health_snapshots_device_id'))
        batch_op.drop_index('ix_device_health_latest')

    op.drop_table('device_health_snapshots')
    with op.batch_alter_table('device_config_diffs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_config_diffs_device_config_diffs_device_id'))

    op.drop_table('device_config_diffs')
    with op.batch_alter_table('compliance_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_results_compliance_results_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_results_compliance_results_rule_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_results_compliance_results_device_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_results_compliance_results_checked_at'))
        batch_op.drop_index('ix_compliance_device_time')

    op.drop_table('compliance_results')
    with op.batch_alter_table('virtual_instance_infos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_virtual_instance_infos_virtual_instance_infos_vm_uuid'))

    op.drop_table('virtual_instance_infos')
    op.drop_table('physical_device_infos')
    with op.batch_alter_table('job_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_tasks_job_tasks_task_type'))
        batch_op.drop_index(batch_op.f('ix_job_tasks_job_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_job_tasks_job_tasks_job_id'))
        batch_op.drop_index(batch_op.f('ix_job_tasks_job_tasks_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_job_tasks_job_tasks_group_id'))
        batch_op.drop_index(batch_op.f('ix_job_tasks_job_tasks_device_id'))
        batch_op.drop_index('ix_job_tasks_device')

    op.drop_table('job_tasks')
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_events_job_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_job_events_job_events_job_id'))
        batch_op.drop_index(batch_op.f('ix_job_events_job_events_event_type'))

    op.drop_table('job_events')
    with op.batch_alter_table('interfaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interfaces_interfaces_mac_address'))
        batch_op.drop_index(batch_op.f('ix_interfaces_interfaces_device_id'))

    op.drop_table('interfaces')
    with op.batch_alter_table('device_tag_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_tag_assignments_device_tag_assignments_tag_id'))
        batch_op.drop_index(batch_op.f('ix_device_tag_assignments_device_tag_assignments_job_id'))
        batch_op.drop_index(batch_op.f('ix_device_tag_assignments_device_tag_assignments_device_id'))
        batch_op.drop_index(batch_op.f('ix_device_tag_assignments_device_tag_assignments_applied_by_id'))

    op.drop_table('device_tag_assignments')
    op.drop_table('device_inventory_groups')
    with op.batch_alter_table('device_config_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_config_snapshots_device_config_snapshots_job_id'))
        batch_op.drop_index(batch_op.f('ix_device_config_snapshots_device_config_snapshots_device_id'))
        batch_op.drop_index(batch_op.f('ix_device_config_snapshots_device_config_snapshots_content_sha256'))
        batch_op.drop_index(batch_op.f('ix_device_config_snapshots_device_config_snapshots_captured_by_id'))
        batch_op.drop_index(batch_op.f('ix_device_config_snapshots_device_config_snapshots_captured_at'))
        batch_op.drop_index('ix_config_job')
        batch_op.drop_index('ix_config_device_time')

    op.drop_table('device_config_snapshots')
    with op.batch_alter_table('audit_log_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_target')
        batch_op.drop_index(batch_op.f('ix_audit_log_entries_audit_log_entries_target_uuid'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entries_audit_log_entries_target_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entries_audit_log_entries_target_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entries_audit_log_entries_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entries_audit_log_entries_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entries_audit_log_entries_job_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entries_audit_log_entries_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entries_audit_log_entries_action'))
        batch_op.drop_index('ix_audit_actor')

    op.drop_table('audit_log_entries')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_type_status')
        batch_op.drop_index(batch_op.f('ix_jobs_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_jobs_scheduled_for'))
        batch_op.drop_index(batch_op.f('ix_jobs_jobs_queue'))
        batch_op.drop_index(batch_op.f('ix_jobs_jobs_owner_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_jobs_operation_template_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_jobs_jobs_idempotency_key'))

    op.drop_table('jobs')
    with op.batch_alter_table('hardware_lifecycle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hardware_lifecycle_hardware_lifecycle_product_model_id'))

    op.drop_table('hardware_lifecycle')
    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_logs_error_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_error_logs_error_logs_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_error_logs_error_logs_correlation_id'))

    op.drop_table('error_logs')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_devices_serial_number'))
        batch_op.drop_index(batch_op.f('ix_devices_devices_name'))
        batch_op.drop_index(batch_op.f('ix_devices_devices_mgmt_ipv4'))
        batch_op.drop_index(batch_op.f('ix_devices_devices_fqdn'))
        batch_op.drop_index(batch_op.f('ix_devices_devices_disabled_at'))

    op.drop_table('devices')
    with op.batch_alter_table('software_lifecycle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_software_lifecycle_software_lifecycle_platform_id'))
        batch_op.drop_index(batch_op.f('ix_software_lifecycle_software_lifecycle_os_name'))
        batch_op.drop_index('ix_softlife_os_platform')
        batch_op.drop_index('ix_softlife_match')

    op.drop_table('software_lifecycle')
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_requestlogs_user')
        batch_op.drop_index('ix_requestlogs_time')
        batch_op.drop_index('ix_requestlogs_status')
        batch_op.drop_index('ix_requestlogs_path')
        batch_op.drop_index(batch_op.f('ix_request_logs_request_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_request_logs_request_logs_status_code'))
        batch_op.drop_index(batch_op.f('ix_request_logs_request_logs_platform_id_hint'))
        batch_op.drop_index(batch_op.f('ix_request_logs_request_logs_path'))
        batch_op.drop_index(batch_op.f('ix_request_logs_request_logs_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_request_logs_request_logs_device_id_hint'))
        batch_op.drop_index(batch_op.f('ix_request_logs_request_logs_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_request_logs_request_logs_auth_subject'))

    op.drop_table('request_logs')
    op.drop_table('product_models')
    with op.batch_alter_table('platform_operation_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_operation_templates_platform_operation_templates_platform_id'))
        batch_op.drop_index(batch_op.f('ix_platform_operation_templates_platform_operation_templates_op_type'))
        batch_op.drop_index('ix_platform_op')

    op.drop_table('platform_operation_templates')
    with op.batch_alter_table('jwt_token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jwt_token_blocklist_jwt_token_blocklist_user_id'))
        batch_op.drop_index(batch_op.f('ix_jwt_token_blocklist_jwt_token_blocklist_jwt_token'))

    op.drop_table('jwt_token_blocklist')
    with op.batch_alter_table('compliance_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_rules_compliance_rules_policy_id'))

    op.drop_table('compliance_rules')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_users_disabled_at'))

    op.drop_table('users')
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platforms_platforms_slug'))
        batch_op.drop_index(batch_op.f('ix_platforms_platforms_disabled_at'))

    op.drop_table('platforms')
    op.drop_table('manufacturers')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_login_attempts_username_created')
        batch_op.drop_index(batch_op.f('ix_login_attempts_login_attempts_username'))
        batch_op.drop_index('ix_login_attempts_ip_created')

    op.drop_table('login_attempts')
    with op.batch_alter_table('inventory_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_groups_inventory_groups_slug'))
        batch_op.drop_index(batch_op.f('ix_inventory_groups_inventory_groups_disabled_at'))
        batch_op.drop_index('ix_inventory_groups_dynamic')

    op.drop_table('inventory_groups')
    op.drop_table('device_types')
    with op.batch_alter_table('device_tags', schema=None) as batch_op:
        batch_op.drop_index('ix_device_tags_slug')
        batch_op.drop_index(batch_op.f('ix_device_tags_device_tags_slug'))

    op.drop_table('device_tags')
    with op.batch_alter_table('device_probe_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_probe_templates_device_probe_templates_slug'))
        batch_op.drop_index(batch_op.f('ix_device_probe_templates_device_probe_templates_disabled_at'))

    op.drop_table('device_probe_templates')
    with op.batch_alter_table('credential_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credential_profiles_credential_profiles_name'))
        batch_op.drop_index(batch_op.f('ix_credential_profiles_credential_profiles_disabled_at'))

    op.drop_table('credential_profiles')
    with op.batch_alter_table('compliance_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_policies_compliance_policies_disabled_at'))

    op.drop_table('compliance_policies')
    with op.batch_alter_table('app_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_events_app_events_occurred_at'))

    op.drop_table('app_events')
    # ### end Alembic commands ###
